version: "2"

networks: 
    default:
        external: 
            name: main

services: 
    cfre9admin:
        build:
            context: .
        image: cfre9admin
        container_name: cfre9admin
        restart: on-failure:4
        ports: 
            - 8080:80
        volumes: 
            - .:/var/www/html
        
        working_dir: /var/www/html
        